services:
  frontend-turnero:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: frontend-turnero
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always