version: '3.8'

services:
  frontend-turnero:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: frontend-turnero
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    networks:
      - turnero-network
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  turnero-network:
    external: true
    name: turnero-network  
